postgres:
  host: "psg"
  port: 5432
  database: "my_database"
  user: "my_user"
  password: "my_password"

redis:
  address: "redisdomain:6379"
  password: ""
  db: 0

http_server:
  port: 8080
  elk_domain: "http://logstash:5044"

grpc_server:
  port: 50051

logger_config:
  min_console_log_level: "info"
  elk: false
  logstash_host: "http://logstash:5044"
